### ISSUE TITLE
vaadin-list-box

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-core#105]
Spec document: https://docs.google.com/document/d/1VC2oyy_g1Zm2Ia2sOrQ6LcrkqZ7610uLxHOK0Gtz91Q/edit

**Comment by jouni** [comment]
What’s the team’s feeling, would it be feasible to extend paper-listbox and paper-item, or do we need to reimplement it ourselves (maybe use iron-menu-behavior at least)?

**Comment by tomivirkki** [comment]
Implementation details:
API should be similar to that of `<vaadin-tabs>`:
```
<vaadin-listbox>
  <vaadin-item>foo</vaadin-item>
  <vaadin-item>bar</vaadin-item>
  <vaadin-item>baz</vaadin-item>
<vaadin-listbox>
```

- Extract mixins from `<vaadin-tabs>` to a shared `vaadin-nav-mixins` /`vaadin-nav` /....
- Create `<vaadin-item>` shared element (should be just a simple container for now)

**Comment by tomivirkki** [comment]
Since not all lists are supposed to be horizontally aligned by default (and flaggable as vertical), the `vertical` property should not be part of the parent mixin. Drop the property from the shared list mixin and move the logic to the level where it's relevant.

Alternatively, change `vertical` property into `orientation`, that can be modified by the implementing element. This would be more lightweight a change but requires a modification to the public API.
