### ISSUE TITLE
<vaadin-tabs>

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-core#130]
Should be nice have a low-level tabs element. :)

**Comment by limonte** [comment]
Hello @abdonrd! `<vaadin-tabs>` is in our end-of-the-year roadmap! Here's the preliminary release schedule for it:

- `alpha` - end of October
- `beta` - middle of November
- `stable` - end of November

Thank you for asking, stay tuned! :)

**Comment by abdonrd** [comment]
Sounds good, thanks @limonte! 👏

**Comment by jouni** [comment]
Right now we are working on this with the name of `vaadin-nav`, as we think it will serve as a more general purpose element that you can also use for creating application navigation bars. It has both horizontal and vertical directions.

We started to think if this could even be used as the menu inside a `vaadin-context-menu`, as it does all the necessary things there (keyboard nav, focused item, activating an item). We could just ignore the “selection” in that case. Otherwise, it seems like it could work there as well.

Because of that, I don’t think we should use “tabs”, but maybe “menu” could be a more general purpose name than “nav”? I’m curious how you associate the naming.

Even with the generic naming, we could still have a simple extension from it to create `vaadin-tabs`.

**Comment by jouni** [comment]
You can play with the first prototype here: https://cdn-origin.vaadin.com/vaadin-nav/manolo-mvp/demo/

**Comment by abdonrd** [comment]
Thanks for the info!

I like the idea of having one low level element (`vaadin-nav`) for navigations and create a simple `vaadin-tabs` on top of it.

**Comment by limonte** [comment]
Thanks for the feedback @abdonrd!

> I like the idea of having one low level element (vaadin-nav) for navigations and create a simple vaadin-tabs on top of it.

A small correction: 
 - low-level element is: `vaadin-nav-item`
 - `vaadin-nav` is actually the new name for `vaadin-tabs`, normally it contains multiple `vaadin-nav-item`s

**Comment by abdonrd** [comment]
Oh, as Jouni had said:

> Even with the generic naming, we could still have a simple extension from it to create `vaadin-tabs`.

How would the tabs be used then?

**Comment by limonte** [comment]
Sorry, @abdonrd I misunderstood your comment. The `vaadin-nav` will be extendable and yes, it'll be possible to create elements like `vaadin-tabs`, `vaadin-menu`, etc. on top of it.

**Comment by jouni** [comment]
Update: we did a bit of a “180” with the plan, and will release `vaadin-tabs` (including `vaadin-tab`) element as the first step. The repo will contain the reusable mixins for now, but we’ll most probably split those out once we start building another element that will use them.
